### ISSUE TITLE
Can't upgload Ğ1 SVG logo on Wikimedia Commons

### ISSUE THREAD

**Issue by M5oul** [duniter/G1#4]
I can't upload the [Ğ1 SVG logo](https://github.com/duniter/G1/blob/master/logo/G1-flare/svg/Logo-g1.flare.svg) on [Wikimedia Commons](https://commons.wikimedia.org/wiki/Special:UploadWizard)

Here the error message:
`CSS non sûr trouvé dans l’élément style d’un fichier SVG téléversé.`

**Comment by devingfx** [comment]
Is it a problem of SVG file to be not accepted by a particular website or the website itself?
The problem is a google font embedded link... Write an ussue to wikimedia commons though !
